### ISSUE TITLE
unable to install modern yarn

### ISSUE THREAD

**Issue by not-ivy** [moonrepo/proto#119] opened 2023-06-02 02:42 UTC
Running `proto install yarn 3.6.0` leaves the output:
```
[ INFO 2023-06-01 19:40:54] proto::commands::install:run  yarn has already been installed at ~\.proto\tools\yarn\1.22.19
```

**Comment by milesj** [comment] 2023-06-02 14:16
@not-ivy This is by design. Yarn 2/3 is meant to be committed to a repo with the `.yarn` folder.

**Closed** 2023-06-03 03:03 UTC
