### ISSUE TITLE
Node version detection ignores the parent directory

### ISSUE THREAD

**Issue by Codpoe** [moonrepo/proto#599] opened 2024-08-26 11:13 UTC
### What version?

0.40.2

### Which command?

proto activate

### What happened?

My global prototools in `~/.proto/.prototools:

```
node = "20.17.0"
```

My directory looks like this:

```
projects
├── packages
│   └── app
│       └── package.json    # engines.node >=14
└── .nvmrc                  # 14
```

When I'm in the `projects/packages/app` directory, executing `node -v` was expected to get v14, but it was actually v20.

I don't know if this is a bug or if it's designed that way?

### Operating system?

MacOS

### Architecture?

arm64

**Comment by milesj** [comment] 2024-08-27 04:44
This is kind of by design right now. Activate only uses `.prototools`, as those files are deterministic, where as tool-specific files are not. I would have to test and see what the performance hit is like.

With that said, the shims _should_ take precedence over things set by activate, and the version should be detected at runtime. What does `PROTO_LOG=trace node -v` show?

**Comment by Codpoe** [comment] 2024-08-27 08:10
Directory structure of demo:
```
proto-demo
├─ a
│     └─ package.json    # engines.node >=14
└─ .nvmrc                # 14
```

trace log in sub directory `a`:

```
➜  a PROTO_LOG=trace node -v  
[DEBUG 2024-08-27 16:05:32.247] proto  Running proto v0.40.2  bin="/Users/xxx/.proto/bin/proto" args=["run", "node", "--", "-v"] shim="node" shim_bin="/Users/xxx/.proto/shims/node" pid=2041
[TRACE 16:05:32.247] starbase::app  Running startup phase 
[DEBUG 16:05:32.248] proto_core::proto  Creating proto environment, detecting store  store="/Users/xxx/.proto"
[TRACE 16:05:32.248] starbase::app  Running analyze phase 
[DEBUG 16:05:32.248] proto::systems  Loading configuration in upwards-global mode 
[DEBUG 16:05:32.249] proto_core::proto_config  Loading .prototools  file="/Users/xxx/.proto/.prototools"
[TRACE 16:05:32.249] starbase_utils::fs  Opening file  file="/Users/xxx/.proto/.prototools"
[TRACE 16:05:32.249] starbase_utils::fs_lock  Locking file  file="/Users/xxx/.proto/.prototools"
[TRACE 16:05:32.249] starbase_utils::fs_lock  Unlocking file  file="/Users/xxx/.proto/.prototools"
[TRACE 16:05:32.249] schematic::config::loader  Loading partial configuration  config="ProtoConfig"
[TRACE 16:05:32.249] schematic::config::loader  Creating layer from source  config="ProtoConfig" source="<code>"
[TRACE 16:05:32.250] schematic::config::loader  Merging partial layers into a final result  config="ProtoConfig"
[DEBUG 16:05:32.250] proto_core::proto_config  Merging loaded configs with global 
[DEBUG 16:05:32.250] proto_core::proto_config  Merged 1 configs 
[DEBUG 16:05:32.250] proto_core::proto_config  Merging loaded configs without global 
[DEBUG 16:05:32.250] proto_core::proto_config  Merged 0 configs 
[TRACE 16:05:32.250] starbase::app  Running execute phase 
[DEBUG 16:05:32.251] proto_core::tool_loader  Finding a configured plugin  tool="node"
[DEBUG 16:05:32.251] proto_core::tool_loader  Using a built-in plugin  plugin="https://github.com/moonrepo/tools/releases/download/node_tool-v0.12.0/node_tool.wasm"
[TRACE 16:05:32.251] warpgate::loader  Creating plugin loader  cache_dir="/Users/xxx/.proto/plugins"
[TRACE 16:05:32.251] warpgate::loader  Loading plugin node  id="node" locator="https://github.com/moonrepo/tools/releases/download/node_tool-v0.12.0/node_tool.wasm"
[TRACE 16:05:32.252] starbase_utils::fs  Reading file metadata  file="/Users/xxx/.proto/plugins/node-dad1cbc99a433f56594101a3298836ae44edf6fc8b855aba481e8934e9c9215d.wasm"
[TRACE 16:05:32.252] warpgate::loader  Plugin already downloaded and cached  id="node" path="/Users/xxx/.proto/plugins/node-dad1cbc99a433f56594101a3298836ae44edf6fc8b855aba481e8934e9c9215d.wasm"
[DEBUG 16:05:32.252] proto_core::tool_loader  Loading WASM plugin  source="/Users/xxx/.proto/plugins/node-dad1cbc99a433f56594101a3298836ae44edf6fc8b855aba481e8934e9c9215d.wasm"
[TRACE 16:05:32.252] warpgate::plugin  Storing plugin identifier  id="node"
[TRACE 16:05:32.252] warpgate::plugin  Storing host environment  id="node" env={"arch":"arm64","libc":"gnu","os":"macos","home_dir":{"path":"/userhome/","virtual_prefix":"/userhome","real_prefix":"/Users/xxx"}}
[TRACE 16:05:32.252] starbase_utils::json  Formatting JSON 
[TRACE 16:05:32.252] proto_core::tool_loader  Storing proto tool configuration  config={"bundled-npm":true}
[DEBUG 16:05:32.252] proto_core::tool  Creating tool node and instantiating plugin 
[DEBUG 16:05:32.252] warpgate::client  Creating HTTP client 
[DEBUG 16:05:32.382] warpgate::client  Created HTTP client 
[TRACE 16:05:32.383] warpgate::plugin  Creating plugin container  id="node"
[TRACE 16:05:32.399] warpgate::plugin  Created plugin container  id="node" plugin="6fd1c505-8de7-4cab-a386-a06465337ce7"
[DEBUG 16:05:32.399] proto_core::tool  Created tool node and its WASM runtime 
[TRACE 16:05:32.399] warpgate::plugin  Calling guest function register_tool  id="node" plugin="6fd1c505-8de7-4cab-a386-a06465337ce7" input={"id":"node"}
[TRACE 16:05:32.399] warpgate::plugin  Called guest function register_tool  id="node" plugin="6fd1c505-8de7-4cab-a386-a06465337ce7" output={"config_schema":{"name":"NodePluginConfig","ty":{"type":"Struct","fields":{"bundled-npm":{"schema":{"ty":{"type":"Boolean"}},"hidden":false,"nullable":false,"optional":true,"read_only":false,"write_only":false},"dist-url":{"schema":{"ty":{"type":"String"}},"hidden":false,"nullable":false,"optional":true,"read_only":false,"write_only":false}},"partial":false}},"inventory":{},"name":"Node.js","plugin_version":"0.12.0","type":"Language"}
[DEBUG 16:05:32.400] proto_core::tool_manifest  Loading manifest.json  file="/Users/xxx/.proto/tools/node/manifest.json"
[TRACE 16:05:32.400] starbase_utils::fs  Opening file  file="/Users/xxx/.proto/tools/node/manifest.json"
[TRACE 16:05:32.400] starbase_utils::fs_lock  Locking file  file="/Users/xxx/.proto/tools/node/manifest.json"
[TRACE 16:05:32.400] starbase_utils::fs_lock  Unlocking file  file="/Users/xxx/.proto/tools/node/manifest.json"
[TRACE 16:05:32.400] proto_core::version_detector  Attempting to find version from .prototools files  tool="node"
[TRACE 16:05:32.400] warpgate::plugin  Calling guest function detect_version_files  id="node" plugin="6fd1c505-8de7-4cab-a386-a06465337ce7" input={}
[TRACE 16:05:32.400] warpgate::plugin  Called guest function detect_version_files  id="node" plugin="6fd1c505-8de7-4cab-a386-a06465337ce7" output={"files":[".nvmrc",".node-version","package.json"],"ignore":["node_modules"]}
[TRACE 16:05:32.400] proto_core::tool  Attempting to detect a version from directory  tool="node" dir="/Users/xxx/Documents/projects/proto-demo/a"
[TRACE 16:05:32.400] starbase_utils::fs  Reading file  file="/Users/xxx/Documents/projects/proto-demo/a/package.json"
[TRACE 16:05:32.401] warpgate::plugin  Calling guest function parse_version_file  id="node" plugin="6fd1c505-8de7-4cab-a386-a06465337ce7" input={"content":"{
  "engines": {
    "node": ">=14"
  }
}","file":"package.json"}
[TRACE 16:05:32.401] warpgate::plugin  Called guest function parse_version_file  id="node" plugin="6fd1c505-8de7-4cab-a386-a06465337ce7" output={"version":">=14"}
[DEBUG 16:05:32.401] proto_core::tool  Detected a version  tool="node" file="/Users/xxx/Documents/projects/proto-demo/a/package.json" version=">=14"
[DEBUG 16:05:32.401] proto_core::version_detector  Detected version from tool's ecosystem  tool="node" version=">=14" file="/Users/xxx/Documents/projects/proto-demo/a/package.json"
[DEBUG 16:05:32.401] proto_core::tool  Resolving a semantic version or alias  tool="node" initial_version=">=14"
[DEBUG 16:05:32.401] proto_core::tool  Loading available versions  tool="node"
[TRACE 16:05:32.401] starbase_utils::fs  Reading file metadata  file="/Users/xxx/.proto/tools/node/remote-versions.json"
[TRACE 16:05:32.401] starbase_utils::fs  Reading file  file="/Users/xxx/.proto/tools/node/remote-versions.json"
[TRACE 16:05:32.401] starbase_utils::json  Reading JSON file  file="/Users/xxx/.proto/tools/node/remote-versions.json"
[TRACE 16:05:32.401] warpgate::plugin  Calling guest function resolve_version  id="node" plugin="6fd1c505-8de7-4cab-a386-a06465337ce7" input={"initial":">=14"}
[TRACE 16:05:32.401] warpgate::plugin  Called guest function resolve_version  id="node" plugin="6fd1c505-8de7-4cab-a386-a06465337ce7" output={}
[TRACE 16:05:32.401] proto_core::version_resolver  Resolving a version with manifest  candidate=">=14"
[TRACE 16:05:32.401] proto_core::version_resolver  Found a requirement, resolving further  requirement=">=14"
[TRACE 16:05:32.401] proto_core::version_resolver  Resolved to locally installed version  version="20.17.0"
[DEBUG 16:05:32.401] proto_core::tool  Resolved to 20.17.0  tool="node" version="20.17.0"
[DEBUG 16:05:32.401] proto_core::tool  Checking if tool is installed  tool="node" install_dir="/Users/xxx/.proto/tools/node/20.17.0"
[DEBUG 16:05:32.401] proto_core::tool  Tool has already been installed, locating binaries and shims  tool="node" install_dir="/Users/xxx/.proto/tools/node/20.17.0"
[DEBUG 16:05:32.401] proto_core::tool  Locating executable for tool  tool="node"
[TRACE 16:05:32.401] warpgate::plugin  Calling guest function locate_executables  id="node" plugin="6fd1c505-8de7-4cab-a386-a06465337ce7" input={"context":{"proto_version":"0.40.3","tool_dir":{"path":"/proto/tools/node/20.17.0","virtual_prefix":"/proto","real_prefix":"/Users/xxx/.proto"},"version":"20.17.0"}}
[TRACE 16:05:32.402] warpgate::plugin  Called guest function locate_executables  id="node" plugin="6fd1c505-8de7-4cab-a386-a06465337ce7" output={"exes_dir":"bin","globals_lookup_dirs":["$PROTO_HOME/tools/node/globals/bin"],"primary":{"exe_path":"bin/node"}}
[DEBUG 16:05:32.402] proto_core::tool  Found an executable  tool="node" exe_path="/Users/xxx/.proto/tools/node/20.17.0/bin/node"
[DEBUG 16:05:32.402] proto::commands::run  Running Node.js  bin="/Users/xxx/.proto/tools/node/20.17.0/bin/node" args=["-v"] pid=2041
[TRACE 16:05:32.402] starbase_utils::fs  Writing file  file="/Users/xxx/.proto/tools/node/20.17.0/.last-used"
v20.17.0
```

**Comment by Codpoe** [comment] 2024-08-27 08:19
`engines.node` may specify a version range, which is not a reliable field for determining the version. I think it would be more reasonable to look for version that match the range from the upper directory, and finally fallback to global config.

**Comment by milesj** [comment] 2024-08-27 21:39
Yeah this is tricky, because it is finding `engines.node`:

```
[TRACE 16:05:32.401] warpgate::plugin  Calling guest function parse_version_file  id="node" plugin="6fd1c505-8de7-4cab-a386-a06465337ce7" input={"content":"{
  "engines": {
    "node": ">=14"
  }
}","file":"package.json"}
```

But since the range is so permissive, `>=14`, it pulls in a large version. In proto, we traverse downwards from the highest installed number, so that's why v20 is being used, since 20 >= 14.

If you want it to actually be v14, then `^14` would be best, or something like `>=14 <20`.

**Comment by Codpoe** [comment] 2024-08-28 03:13
By the way, proto is a really great project, but I am a bit confused about the config mode `upwards` and `upwards-global`. May I ask why we need `upwards-global`? In my usage scenario, `~/.prototools` in the userhome directory can already meet my needs well.

**Comment by milesj** [comment] 2024-08-28 03:40
@Codpoe It's mainly for legacy reasons that the "global config" is in `~/.proto` instead of just being in `~`.

**Comment by Codpoe** [comment] 2024-08-28 13:03
Mixing `~/.proto/.prototools` and `~/.prototools` can be confusing for me 😂:

- if I set `bundled-npm = true` in the global `~/.proto/.prototools`, it will have no effect because the default config mode of the install command is `upwards`, it will not read the global config file.

- If local & userhome `.prototools` does not exist, the node version in the global config `~/.proto/.prototools` will be changed every time `proto install node <version>` is executed, because proto does not read the existing node version from the global.

Therefore, I personally prefer to use only `~/.prototools` for global configuration. However, this method also has a point that I find a bit troublesome, which is that I cannot easily set the global version of the tools. It seems that I can only manually edit `~/.prototools`.

**Comment by milesj** [comment] 2024-08-28 15:05
That's a good point, let me think about this.

It's a hard balance to hit, as some commands shouldn't inherit global by default, like `proto install/use`.

**Comment by Codpoe** [comment] 2024-08-29 02:42
Why shouldn't the `install` command inherit the global?

**Comment by milesj** [comment] 2024-08-29 03:16
Every tool that gets installed for the first time pins a version into the global config. If I'm a repo/project owner and I want to pin what tools are required for the repo, say only node/npm, then users can go to the project and run `proto install` to get setup for those 2 tools.

If we include global by default, it could install N tools which is typically what the user doesn't want.

**Comment by milesj** [comment] 2024-08-29 16:25
Yeah good point. I agree that this whole flow still isn't the best. There's a lot of patterns to try and support.

**Comment by milesj** [comment] 2024-10-08 23:44
Gonna close this for now since the original issue is resolved.

**Closed by milesj** 2024-10-08 23:44 UTC
Labels: bug
